# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87b3f50129130fab5b690481a0d9e62084ba69c1d8750f5023da5c2029a094579cb5b64babb1fb1ac79e57c9b89efd4565b6de6d09fb7bce193676aa064816dd

test:
  secret_key_base: 43d85fe3d6e31b92129590bf30bfdcc04dc08a08f02417a418ca5b50204bf076cbaa4e03f2d6d06439758e6869ea562690b8070f286d4cfbbd51609a530add22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
